### ISSUE TITLE
Techniques and martial arts broken

### ISSUE THREAD

**Issue by YourCompanionCube** [chaosvolt/cdda-arcana-mod#137] opened 2020-04-22 16:54 UTC
there seems to have been a formatting change and several mods including this throw errors in regards to any techniques or martial arts
```

 DEBUG    : Error: data/mods//Arcana/martialarts.json: line 89:27: tried to start object, but found '[', not '{'

        "max_stacks": 1,
        "bonus_dodges": 2,
        "flat_bonuses": [ [
                          ^
                            "dodge", 1.0 ] ]
      },
      {


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 820

```
and once that is fixed:
```
 DEBUG    : Error: data/mods//Arcana/martialarts.json: line 89:38: expected pair separator ':', not '1'

        "max_stacks": 1,
        "bonus_dodges": 2,
        "flat_bonuses": [ { "dodge", 1
                                     ^
                                      .0 } ]
      },
      {


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 820
```

**Comment by chaosvolt** [comment] 2020-04-22 18:04
Update arcana, duplicate of https://github.com/chaosvolt/cdda-arcana-mod/issues/129 and was fixed by https://github.com/chaosvolt/cdda-arcana-mod/pull/130

**Closed by chaosvolt** 2020-04-22 18:04 UTC
