### ISSUE TITLE
Dementia's no longer exist?

### ISSUE THREAD

**Issue by nivilack** [chaosvolt/cdda-arcana-mod#147] opened 2020-07-28 18:21 UTC
DEBUG    : Error: line 48:21: no such monster

        { "monster": "mon_dementia", "x": 9, "y": 7, "repeat": [ 1, 4 ] },
        { "monster": "mon_dementia", "x": 17, "y": 11, "repeat": [ 1, 3 ] },
        { "monster":
                    ^
                     "mon_homunculus", "x": 5, "y": 16, "repeat": 1 }
      ]
    }

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1149

The Game crashes after this message.

**Comment by chaosvolt** [comment] 2020-07-28 20:39
Incorrect monster, it's complaining about homunculi. Update arcana, reminder that the launcher does not update third-party mods for you, and that "update game" only touches your build of CDDA.

The cause is this CDDA change: https://github.com/CleverRaven/Cataclysm-DDA/pull/42431which removed some monsters that were in vanilla but never used.

It was preemptively fixed via https://github.com/chaosvolt/cdda-arcana-mod/commit/218592aefeaad6d658a54e0124bfaa551bc0eb43 absorbing their JSON into Arcana before that PR was even merged.

**Closed by chaosvolt** 2020-07-28 20:39 UTC

**Comment by nivilack** [comment] 2020-07-29 04:51
Ah I see. I thought I had the latest update. My bad and thank you much.

**Comment by chaosvolt** [comment] 2020-07-29 15:06
No worries.
