### ISSUE TITLE
Cannot wear tool_armor with artifact qualities

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [chaosvolt/cdda-arcana-mod#23] opened 2017-12-24 05:01 UTC
Don't know when it happened, but all armor with artifact data is unwearable on or no.

**Comment by chaosvolt** [comment] 2017-12-24 19:57
What the...oh you've got to be fucking kidding me. Report it on the CDDA repo because that is almost certainly a source fuckup on their part.

**Comment by chaosvolt** [comment] 2017-12-24 20:00
Also pinging @Coolthulhu because they're likely to know what did this, and whether this can be fixed on my end.

**Comment by chaosvolt** [comment] 2017-12-24 20:46
Um. @BorkBorkGoesTheCode mind confirming this? I'm testing this with latest build and failing to replicate this.

I DID find a bug in my testing so far though:
![image](https://user-images.githubusercontent.com/11582235/34329126-f4f21cee-e8b8-11e7-87df-00b9002c8e03.png)

**Comment by Coolthulhu** [comment] 2017-12-24 20:46
Old save?
The only two changes I recall were:
* Not saving duplicate entries for static artifacts. Some old save might rely on the duplicates to update artifacts. Try finding the artifact save file and deleting the entry for the artifact that is also static.
* Artifacts got actual finalization run. This should only really affect random artifacts.

**Comment by chaosvolt** [comment] 2017-12-24 20:48
Strange. Yeah I'm not able to replicate this with a fresh save. But I can see no sane reason why old saves might break suddenly. Lemme try saving this game then repeating my tests just in case.

**Comment by chaosvolt** [comment] 2017-12-24 20:53
I DID however discover I fucked up and never noticed that I didn't add the effects that certain magic signs grant on use, and got the names confused when adding the jade wreath.

**Comment by chaosvolt** [comment] 2017-12-24 22:22
Fixed the thing in https://github.com/chaosvolt/cdda-arcana-mod/commit/aed6ead2ccacd3118c9ae1fea10a8436fe182558, poke me if the issue itself crops up.

**Closed by chaosvolt** 2017-12-24 22:22 UTC
Labels: Confirmation Needed

**Comment by BorkBorkGoesTheCode** [comment] 2017-12-25 05:31
Here are two copies of wyrmskin armor in the debug menu:
![screenshot 465](https://user-images.githubusercontent.com/18560216/34333337-44037c68-e901-11e7-9515-03995c5450f6.png)
![screenshot 464](https://user-images.githubusercontent.com/18560216/34333340-46d2e398-e901-11e7-9242-dbba56cc0a71.png)

Here's what happens when I pick up the wyrmskin armor:
![screenshot 466](https://user-images.githubusercontent.com/18560216/34333358-5dde38ee-e901-11e7-8654-802ef2c37df1.png)
The wear option is grayed out. The inventory screen wear option is also grayed out.

The problem isn't present after replacing the old mod with the latest version of Arcana. It does seem to be an issue with an old save, since the issue remains in the older ones even after updating.

**Comment by chaosvolt** [comment] 2017-12-25 07:29
The two copies thing is weird, but yeah. I've noticed that in debug, and have no idea what the cause is. It seems to have no effect on the items in their normal environment.

As for old saves I'll have to keep an eye out for it in the succession game we've been doing at Utterly Mad, it seems...
