### ISSUE TITLE
Error: data/mods//Arcana/arcana.json: line 17:3: member not found: display_category

### ISSUE THREAD

**Issue by animethecat** [chaosvolt/cdda-arcana-mod#79] opened 2019-09-05 14:32 UTC
When creating a new character in a new world with the latest Experimental build, I get the following error code and then returned to the title screen:
 DEBUG    : Error: data/mods//Arcana/arcana.json: line 17:3: member not found: display_category

    "cut_dmg_verb": "damaged"
  },
  {
  ^

    "type": "skill",
    "ident": "magic",

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 710

**Comment by animethecat** [comment] 2019-09-05 14:34
error exists even when creating a world with only the Dark Days Ahead, Disable NPC Needs, and Arcana and Magic Items Mods loaded. Has existed on previous versions but currently is happening with build 9590.

**Comment by chaosvolt** [comment] 2019-09-05 17:12
Three questions:
1. Did you update arcana?
2. Do you use the launcher?
3. If yes to question 2, have you tried updating arcana without using the launcher?

This was fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/468cfb4df5377e49c3c64dad8dec8ea808c6f1d5 almost a week ago.

**Closed by chaosvolt** 2019-09-05 17:12 UTC

**Comment by animethecat** [comment] 2019-09-05 18:20
1. Yep, downloaded the most current version from here.
2. I do, but...
3. I did this (and always do this). Removed the folder in mods that the Launcher puts there, then copy-pasted the mod from the download in 1 (unzipped) into the mods folder, reloaded the game, created a new world with only the Arcana mod, DDA, and Disable NPC needs active.

I can try removing everything and then reinstalling though.

**Comment by chaosvolt** [comment] 2019-09-05 18:29
Are you certain? I've been unable to reproduce this since adding the requested property to the skill entry, which was a simple single-line fix.

**Comment by chaosvolt** [comment] 2019-09-05 18:35
That does seem odd that it'd be acting up even after grabbing it from here, though. I thought the launcher was explicitly not able to grab and override third-party mods unless the user tells it to, so it shouldn't be automatically overriding it (it used to do that for mods that existed as both third-party and in-repo mods, but that's why Arcana and PK's were removed from the repo a while after they were obsoleted).

Indeed, the fact it doesn't do anything mod-related unless the user tells it to is usually why most of my "this bug was already fixed" issues are by launcher tells it to, but now I'm not sure what the cause is...

**Comment by animethecat** [comment] 2019-09-05 19:47
Ok, uninstalled the launcher, fetched the latest launcher version, uninstalled the game files and pulled the latest experimental (9590 still), loaded up the game, and still got the same error. I deleted the Arcana mod within the launcher window so that it didn't try to fetch it, then made sure I had your mod downloaded in its most current version. I got the same error. Is there any way I can compile my game and deliver it to you? 9/10 chance I'm not doing something properly, but I'm not an expert haha

**Comment by animethecat** [comment] 2019-09-05 19:53
well... I did all of that a third time and now it works... The only thing I can think is that I accidentally copied the file from the installer, rather than deleted it, and replaced the version I downloaded with it on accident. It works now, so I think the whole affair was user error.

**Comment by chaosvolt** [comment] 2019-09-05 19:59
Not sure, in my experience the launcher seems to be rather user-unfriendly. @.@
