### ISSUE TITLE
Flesh angels can escape glowing candles square in arcanists' house.

### ISSUE THREAD

**Issue by Dracque** [chaosvolt/cdda-arcana-mod#425] opened 2024-05-12 09:52 UTC
Seen a few flesh angels roam around towns, as far as I remember there was a house with a glowing candles square nearby in all instances. Wander spawns are on.

Example of missing flesh angel in house. One was spotted about 2 houses away on a road on the same day.
![Emil _2024-05-12_09-33-34_+0100](https://github.com/chaosvolt/cdda-arcana-mod/assets/167656683/6cfb3ce9-5bfb-408a-b087-b1270b077151)

**Comment by chaosvolt** [comment] 2024-05-12 17:08
Hmm. Are you playing with the 3D vision setting on? My only guess is that once again the game is bugging out and letting flying enemies clip through ceilings again...

**Comment by Dracque** [comment] 2024-05-12 17:40
I am indeed playing with 3D vision on. I'll turn it off and see if I can reproduce the issue.

**Comment by Dracque** [comment] 2024-05-12 18:38
Turned off Experimental 3D field of vision, found a house with a trapped flesh angel then waited a few hours several map tiles away. The monster was still trapped. Waited a few days further away and now the flesh angel is gone.
![Debug Dan _2024-05-12_18-34-10_+0100](https://github.com/chaosvolt/cdda-arcana-mod/assets/167656683/97869d3a-250d-46dc-acfb-e125efe12d29)

**Comment by chaosvolt** [comment] 2024-05-12 19:56
Oh now that's...cursed. Not sure what else could be causing that, hmm. Horde mode behavior maybe but I'm not sure if flesh angels count as zombies for the sake of getting sucked up into a horde. If it's not slipping past when you're there in the reality bubble then it shouldn't be an issue with the barrier furniture itself or the ceiling, but hmm.

**Comment by chaosvolt** [comment] 2024-05-13 16:16
The only other thing I can think of is to test if removing the `FLIES` flag helps, or testing whether it was related to having wander spawns/horde mode on.

**Comment by Dracque** [comment] 2024-05-13 17:33
Turned off wander spawns. Created a new world with just default mods and Arcana.
Found a trapped flesh angel. Waited about two days far away (house was not visible on map unless fully zoomed out) and monster was still here. Waited another few days at the same distance and flesh angel was still trapped.

Don't know how to remove a flag from a monster but standing on the roof right above the inside of the candle square and spamming a compressed air horn did not result in the character getting mauled. Not sure if that's useful info.

Moreover, the house had a few dementia inside before the first time skip and stayed in after both wait. I'm used to seeing a dementia or two roam outside either right next to the house or on the street.

**Comment by chaosvolt** [comment] 2024-05-13 17:50
Sounds like the issue is more likely to be wander spawns behavior I'm guessing. Unfortunate since that means only fix I can think of is diving into the code and chucking a PR at BN that tries to check if a monster is in some way stuck, but not sure of the easiest way to do that.

I encountered some similar fun weirdness previously, where the tentacle boss from the collapsed office tower had migrated out into the open despite being unable to actually move, which I later on fixed via https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4205

**Comment by Dracque** [comment] 2024-05-13 18:44
Looking at the linked fix it seems that monsters can be excluded if needed.
Assuming I understood:
"type.id == mtype_id( "mon_jabberwock" ) || // Jabberwockies are an exception."

Could it work with Arcana or would that create more problems ?

**Comment by chaosvolt** [comment] 2024-05-13 21:26
It's hardcoded, but I could do something wacky like PR in support for a monster flag specifically for excluding critters from horde mode behavior. Might be useful for any case where the game intends to have a boss monster that's not fixed in one spot but should still stay in its lair.

**Comment by Dracque** [comment] 2024-05-14 15:04
If messing with the code itself isn't ideal it might be worth checking if the summoned variant gets added to hordes. If I'm not mistaken one of the ruins has a trapped "summoned shoggoth" and I don't think I've ever seen one in the wild. Would still need to verify just in case though.

**Comment by chaosvolt** [comment] 2024-05-14 16:52
Looks like summoned critters get excluded since the horde function only picks up monsters with the `ZOMBIE` species, and all summons have their species overridden to `ARCANA_SUMMONED`.

**Comment by Dracque** [comment] 2024-05-14 16:58
Is swapping the flesh angel trapped in the house to its summoned variant a solution to the bug or would it break something ?

**Comment by chaosvolt** [comment] 2024-05-14 17:16
That'd be reasonable yeah, just means the player misses out on what it'd drop normally when killed. Guess I could just go with that if I don't get time to mess with some improvements to the underlying code.

**Comment by chaosvolt** [comment] 2024-05-18 20:13
Aight, bit belatedly https://github.com/chaosvolt/cdda-arcana-mod/commit/8f97cd53b8f33d3d0d7fe9abc4091c35a9f60926 should fix this for now. Ideally I'd like to just make monster horde code a bit more robust, but swapping it for a summoned flesh angel should be a good band-aid for the time being.

**Closed by chaosvolt** 2024-05-18 20:13 UTC
